"""Build report.html and report.md from findings.json, merging review.json when it exists.

review.json (written by the reviewing agent; every field optional):
    {"summary": "...", "study_type": "...", "guideline": "CONSORT 2025",
     "dismissed": [{"id": "S3", "reason": "..."}],
     "edits": {"S2": {"order": "first", "fix": "...", "calculation": "..."}},
     "findings": [{"title", "group", "severity", "order", "where", "quote", "evidence", "calculation", "fix"}],
     "guideline_items": [{"item": "...", "status": "reported|missing|unclear", "where": "..."}],
     "not_verified": [{"item": "...", "reason": "..."}]}
"""
from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from .catalog import GROUPS

L = {
    "en": {"title": "Paper Fact Check report", "summary": "Summary", "first": "Change a conclusion",
           "major": "Worth fixing", "minor": "Minor", "nv": "Could not verify", "findings": "Findings",
           "where": "Where", "quote": "Quoted text", "evidence": "What contradicts it", "calc": "Check",
           "fix": "Suggested fix", "context": "Passage", "computed": "computed", "reviewed": "reviewed",
           "first_order": "changes a conclusion", "second_order": "does not change a conclusion",
           "statements": "Declarations", "found": "found", "notfound": "not found", "refs": "Reference lookups",
           "ref_status": {"verified": "verified", "problem": "problem", "not_found": "not found",
                          "unverifiable": "not checked"},
           "dismissed": "Dismissed on review", "reason": "Reason", "none": "No findings in this group.",
           "guideline": "Reporting checklist", "item": "Item", "status": "Status", "nofindings":
           "No findings. Every check that could run found the paper consistent with itself.",
           "study": "Study type", "generated": "Generated by Paper Fact Check", "paper": "Paper",
           "stmt": {"ethics_approval": "Ethics approval", "informed_consent": "Informed consent",
                    "conflict_of_interest": "Competing interests", "funding": "Funding",
                    "data_availability": "Data availability", "code_availability": "Code availability",
                    "trial_registration": "Trial or review registration", "author_contributions": "Author contributions",
                    "ai_use_disclosure": "Use of AI tools", "reporting_guideline": "Reporting guideline named"},
           "intro": "Each finding quotes the paper and shows what contradicts it. Findings marked computed were "
                    "calculated by script; findings marked reviewed come from reading the paper."},
    "zh": {"title": "Paper Fact Check 核查报告", "summary": "总览", "first": "会改变结论", "major": "值得修改",
           "minor": "次要", "nv": "无法核实", "findings": "发现", "where": "位置", "quote": "原文",
           "evidence": "和它矛盾的证据", "calc": "核算", "fix": "修改建议", "context": "上下文",
           "computed": "程序计算", "reviewed": "通读发现", "first_order": "影响结论", "second_order": "不影响结论",
           "statements": "声明", "found": "有", "notfound": "未找到", "refs": "文献逐条核查",
           "ref_status": {"verified": "已核实", "problem": "有问题", "not_found": "查不到", "unverifiable": "未核查"},
           "dismissed": "复核后排除", "reason": "理由", "none": "这一类没有发现。",
           "guideline": "报告规范逐项", "item": "条目", "status": "状态",
           "nofindings": "没有发现。能运行的检查都显示论文前后一致。", "study": "研究类型",
           "generated": "由 Paper Fact Check 生成", "paper": "论文",
           "stmt": {"ethics_approval": "伦理审批", "informed_consent": "知情同意", "conflict_of_interest": "利益冲突",
                    "funding": "基金资助", "data_availability": "数据可得性", "code_availability": "代码可得性",
                    "trial_registration": "试验或综述注册", "author_contributions": "作者贡献",
                    "ai_use_disclosure": "AI 工具使用声明", "reporting_guideline": "注明的报告规范"},
           "intro": "每条发现都引用原文，并给出与之矛盾的证据。标为“程序计算”的由脚本算出，标为“通读发现”的来自逐段阅读。"},
}

SEV_ZH = {"critical": "严重", "major": "重要", "minor": "次要"}


def merge(out: Path) -> dict[str, Any]:
    result = json.loads((out / "findings.json").read_text(encoding="utf-8"))
    review_path = out / "review.json"
    review: dict[str, Any] = json.loads(review_path.read_text(encoding="utf-8")) if review_path.is_file() else {}
    by_id = {f["id"]: f for f in result["findings"]}
    for fid, edit in (review.get("edits") or {}).items():
        if fid in by_id:
            by_id[fid].update({k: v for k, v in edit.items() if k not in ("id", "source")})
    dismissed_ids = {d.get("id"): d.get("reason", "") for d in review.get("dismissed") or []}
    kept, dismissed = [], []
    for f in result["findings"]:
        if f["id"] in dismissed_ids:
            dismissed.append({**f, "reason": dismissed_ids[f["id"]]})
        else:
            kept.append(f)
    for i, f in enumerate(review.get("findings") or [], 1):
        kept.append({"id": f"R{i}", "source": "review", "group": f.get("group", "claims"),
                     "severity": f.get("severity", "major"), "order": f.get("order", "second"),
                     **{k: f.get(k, "") for k in ("title", "where", "quote", "evidence", "calculation", "fix", "context")}})
    rank = {"critical": 0, "major": 1, "minor": 2}
    kept.sort(key=lambda f: (f.get("order") != "first", rank.get(f.get("severity"), 3)))
    result.update(findings=kept, dismissed=dismissed, review=review)
    result["not_verified"] = result.get("not_verified", []) + list(review.get("not_verified") or [])
    return result


def _e(s: Any) -> str:
    return html.escape(str(s or ""))


def _counts(findings: list[dict]) -> tuple[int, int, int]:
    first = sum(f.get("order") == "first" for f in findings)
    major = sum(f.get("order") != "first" and f.get("severity") in ("critical", "major") for f in findings)
    return first, major, len(findings) - first - major


CSS = """
:root{--ink:#1d2433;--mute:#5b6475;--line:#e3e6ec;--bg:#f7f8fa;--crit:#b42318;--maj:#c2410c;--min:#475569;--ok:#15803d;--acc:#1f4fd1}
*{box-sizing:border-box}body{margin:0;font:15px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif;color:var(--ink);background:#fff}
nav{position:fixed;top:0;left:0;bottom:0;width:250px;overflow:auto;background:var(--bg);border-right:1px solid var(--line);padding:22px 16px}
nav .brand{font-weight:700;font-size:15px;margin-bottom:14px}nav a{display:block;color:var(--mute);text-decoration:none;padding:3px 8px;border-radius:6px;font-size:13.5px}
nav a:hover{background:#eceff4;color:var(--ink)}nav .n{float:right;color:#98a1b2}nav .sub{padding-left:20px;font-size:12.5px}
main{margin-left:250px;padding:34px 48px 80px;max-width:1010px}h1{font-size:25px;margin:0 0 4px}h2{font-size:19px;margin:38px 0 12px;padding-top:6px;border-top:1px solid var(--line)}
.meta{color:var(--mute);font-size:13.5px}.tiles{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}
.tile{border:1px solid var(--line);border-radius:10px;padding:12px 14px}.tile b{display:block;font-size:26px;line-height:1.2}.tile span{color:var(--mute);font-size:13px}
.tile.first b{color:var(--crit)}.tile.major b{color:var(--maj)}.tile.minor b{color:var(--min)}
.verdict{background:var(--bg);border-left:3px solid var(--acc);padding:10px 14px;border-radius:0 8px 8px 0}
.card{border:1px solid var(--line);border-radius:10px;padding:14px 16px;margin:12px 0}.card h3{font-size:15.5px;margin:0 0 8px}
.badge{display:inline-block;font-size:12px;padding:1px 8px;border-radius:99px;margin-right:6px;border:1px solid}
.b-critical{color:var(--crit);border-color:#f3b4ae;background:#fef3f2}.b-major{color:var(--maj);border-color:#f9c7a5;background:#fff6ed}
.b-minor{color:var(--min);border-color:#cbd2dc;background:#f6f7f9}.b-first{color:#fff;background:var(--crit);border-color:var(--crit)}
.b-src{color:var(--mute);border-color:var(--line)}.id{color:#98a1b2;font-size:12.5px;margin-right:6px}
dl{display:grid;grid-template-columns:112px 1fr;gap:4px 12px;margin:6px 0 0}dt{color:var(--mute);font-size:13px}dd{margin:0}
blockquote{margin:0;padding:4px 10px;border-left:3px solid #d0d5dd;background:#fafbfc;font-size:14px}
.calc{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13.5px;background:#f3f5f9;padding:2px 6px;border-radius:5px}
.fix{background:#ecfdf3;border-left:3px solid var(--ok);padding:4px 10px}details{margin-top:6px}summary{cursor:pointer;color:var(--mute);font-size:13px}
table{border-collapse:collapse;width:100%;font-size:13.5px;margin:8px 0}th,td{border-bottom:1px solid var(--line);padding:6px 8px;text-align:left;vertical-align:top}
th{color:var(--mute);font-weight:600}.ok{color:var(--ok)}.no{color:var(--maj)}.muted{color:var(--mute)}
footer{margin-top:50px;color:#98a1b2;font-size:12.5px}
@media(max-width:900px){nav{position:static;width:auto;border:0}main{margin:0;padding:20px}.tiles{grid-template-columns:repeat(2,1fr)}}
@media print{nav{display:none}main{margin:0}}
"""


def _card(f: dict, t: dict, lang: str) -> str:
    sev = f.get("severity", "minor")
    sev_label = SEV_ZH.get(sev, sev) if lang == "zh" else sev
    rows = []
    for key, label in (("where", t["where"]), ("quote", t["quote"]), ("evidence", t["evidence"]),
                       ("calculation", t["calc"]), ("fix", t["fix"])):
        v = f.get(key)
        if not v:
            continue
        if key == "quote":
            body = f"<blockquote>{_e(v)}</blockquote>"
        elif key == "calculation":
            body = f'<span class="calc">{_e(v)}</span>'
        elif key == "fix":
            body = f'<div class="fix">{_e(v)}</div>'
        else:
            body = _e(v)
        rows.append(f"<dt>{label}</dt><dd>{body}</dd>")
    ctx = f.get("context")
    more = f"<details><summary>{t['context']}</summary><blockquote>{_e(ctx)}</blockquote></details>" \
        if ctx and ctx != f.get("quote") else ""
    order = f'<span class="badge b-first">{t["first_order"]}</span>' if f.get("order") == "first" else ""
    src = t["computed"] if f.get("source") == "script" else t["reviewed"]
    return (f'<div class="card" id="{_e(f["id"])}"><h3><span class="id">{_e(f["id"])}</span>{_e(f.get("title"))}</h3>'
            f'{order}<span class="badge b-{sev}">{_e(sev_label)}</span><span class="badge b-src">{src}</span>'
            f'<dl>{"".join(rows)}</dl>{more}</div>')


def html_report(r: dict[str, Any], lang: str) -> str:
    t = L[lang]
    findings = r["findings"]
    first, major, minor = _counts(findings)
    review = r.get("review") or {}
    groups = [g for g in GROUPS if any(f.get("group") == g for f in findings)]
    nav = [f'<div class="brand">Paper Fact Check</div><a href="#summary">{t["summary"]}</a>']
    body = [f'<h1>{t["title"]}</h1><div class="meta">{t["paper"]}: {_e(r["paper"])} · {_e(r["generated"][:16])}'
            + (f' · {t["study"]}: {_e(review.get("study_type"))}' if review.get("study_type") else "") + "</div>",
            f'<h2 id="summary">{t["summary"]}</h2>',
            f'<div class="tiles"><div class="tile first"><b>{first}</b><span>{t["first"]}</span></div>'
            f'<div class="tile major"><b>{major}</b><span>{t["major"]}</span></div>'
            f'<div class="tile minor"><b>{minor}</b><span>{t["minor"]}</span></div>'
            f'<div class="tile"><b>{len(r.get("not_verified", []))}</b><span>{t["nv"]}</span></div></div>']
    if review.get("summary"):
        body.append(f'<p class="verdict">{_e(review["summary"])}</p>')
    body.append(f'<p class="muted">{t["intro"]}</p>')
    if not findings:
        body.append(f"<p>{t['nofindings']}</p>")
    for g in groups:
        items = [f for f in findings if f.get("group") == g]
        name = GROUPS[g][1 if lang == "zh" else 0]
        nav.append(f'<a href="#g-{g}">{name}<span class="n">{len(items)}</span></a>')
        nav += [f'<a class="sub" href="#{_e(f["id"])}">{_e(f["id"])} {_e(str(f.get("title"))[:28])}</a>' for f in items[:12]]
        body.append(f'<h2 id="g-{g}">{name}</h2>' + "".join(_card(f, t, lang) for f in items))
    gi = review.get("guideline_items") or []
    if gi:
        nav.append(f'<a href="#guideline">{t["guideline"]}</a>')
        rows = "".join(f'<tr><td>{_e(i.get("item"))}</td><td class="{"ok" if i.get("status") == "reported" else "no"}">'
                       f'{_e(i.get("status"))}</td><td>{_e(i.get("where"))}</td></tr>' for i in gi)
        body.append(f'<h2 id="guideline">{t["guideline"]}: {_e(review.get("guideline"))}</h2>'
                    f'<table><tr><th>{t["item"]}</th><th>{t["status"]}</th><th>{t["where"]}</th></tr>{rows}</table>')
    nav.append(f'<a href="#statements">{t["statements"]}</a>')
    rows = "".join(f'<tr><td>{t["stmt"].get(s["statement"], s["statement"])}</td>'
                   f'<td class="{"ok" if s["found"] else "no"}">{t["found"] if s["found"] else t["notfound"]}</td>'
                   f'<td class="muted">{_e(s["quote"][:220])}</td></tr>' for s in r.get("statements", []))
    body.append(f'<h2 id="statements">{t["statements"]}</h2><table>{rows}</table>')
    refs = r.get("references") or {}
    if refs.get("items"):
        nav.append(f'<a href="#refs">{t["refs"]}<span class="n">{refs["total"]}</span></a>')
        rows = "".join(f'<tr><td>{_e(i["label"])}</td><td class="{"ok" if i["status"] == "verified" else "no" if i["status"] != "unverifiable" else "muted"}">'
                       f'{t["ref_status"].get(i["status"], i["status"])}</td><td>{_e(i["reference"][:180])}'
                       + (f'<div class="muted">→ {_e((i.get("matched") or {}).get("title", ""))[:140]}</div>'
                          if i.get("matched") and i["matched"].get("title") else "")
                       + "</td></tr>" for i in refs["items"])
        body.append(f'<h2 id="refs">{t["refs"]}</h2><table>{rows}</table>')
    if r.get("not_verified"):
        nav.append(f'<a href="#nv">{t["nv"]}</a>')
        body.append(f'<h2 id="nv">{t["nv"]}</h2><ul>' + "".join(
            f"<li><b>{_e(n.get('item'))}</b>" + (f": {_e(n.get('reason'))}" if n.get("reason") else "") + "</li>"
            for n in r["not_verified"]) + "</ul>")
    if r.get("dismissed"):
        nav.append(f'<a href="#dismissed">{t["dismissed"]}</a>')
        body.append(f'<h2 id="dismissed">{t["dismissed"]}</h2><table><tr><th></th><th>{t["findings"]}</th><th>{t["reason"]}</th></tr>'
                    + "".join(f'<tr><td>{_e(d["id"])}</td><td>{_e(d.get("title"))}<div class="muted">{_e(d.get("quote", "")[:160])}</div></td>'
                              f'<td>{_e(d.get("reason"))}</td></tr>' for d in r["dismissed"]) + "</table>")
    body.append(f'<footer>{t["generated"]} {_e(r["version"])} · https://github.com/Biajin-PKU/paper-fact-check</footer>')
    return (f'<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" '
            f'content="width=device-width,initial-scale=1"><title>{t["title"]}: {_e(r["paper"])}</title>'
            f'<style>{CSS}</style></head><body><nav>{"".join(nav)}</nav><main>{"".join(body)}</main></body></html>')


def md_report(r: dict[str, Any], lang: str) -> str:
    t = L[lang]
    first, major, minor = _counts(r["findings"])
    review = r.get("review") or {}
    out = [f"# {t['title']}: {r['paper']}", "",
           f"**{first}** {t['first']} · **{major}** {t['major']} · **{minor}** {t['minor']} · "
           f"**{len(r.get('not_verified', []))}** {t['nv']}", ""]
    if review.get("summary"):
        out += [review["summary"], ""]
    for g in GROUPS:
        items = [f for f in r["findings"] if f.get("group") == g]
        if not items:
            continue
        out += [f"## {GROUPS[g][1 if lang == 'zh' else 0]}", ""]
        for f in items:
            sev = SEV_ZH.get(f["severity"], f["severity"]) if lang == "zh" else f["severity"]
            order = t["first_order"] if f.get("order") == "first" else t["second_order"]
            out.append(f"### {f['id']}. {f.get('title')} [{sev} · {order}]")
            for key, label in (("where", t["where"]), ("quote", t["quote"]), ("evidence", t["evidence"]),
                               ("calculation", t["calc"]), ("fix", t["fix"])):
                if f.get(key):
                    out.append(f"- **{label}:** " + (f"> {f[key]}" if key == "quote" else
                                                      f"`{f[key]}`" if key == "calculation" else f[key]))
            out.append("")
    missing = [t["stmt"].get(s["statement"], s["statement"]) for s in r.get("statements", []) if not s["found"]]
    if missing:
        out += [f"## {t['statements']}", "", f"{t['notfound']}: " + ", ".join(missing), ""]
    if r.get("not_verified"):
        out += [f"## {t['nv']}", ""] + [f"- {n.get('item')}" + (f": {n.get('reason')}" if n.get("reason") else "")
                                         for n in r["not_verified"]] + [""]
    return "\n".join(out)


def render(out: Path, lang: str | None = None) -> list[Path]:
    r = merge(out)
    lang = lang or r.get("language", "en")
    lang = lang if lang in L else "en"
    (out / "report.html").write_text(html_report(r, lang), encoding="utf-8")
    (out / "report.md").write_text(md_report(r, lang), encoding="utf-8")
    return [out / "report.html", out / "report.md"]
